### ISSUE TITLE
Incorrect example in docs

### ISSUE THREAD

**Issue by CramericaIndustries** [ajnisbet/opentopodata#40]
Hello and thank you for that wonderful project!

I found a mistake in your documentation where you describe how to define a multi dataset in `config.yaml` file. [https://www.opentopodata.org/notes/multiple-datasets/](https://www.opentopodata.org/notes/multiple-datasets/)

This didn't work for me:
```
# Hi-res New Zealand.
- name: nzdem8m
  path: data/nzdem8m/
  filename_tile_size: 65536
  filename_epsg: 2193

# Mapzen global.
- name: mapzen
  path: data/mapzen/


# NZ with mapzen fallback.
-name: nz-global
  - child_datasets:
    - nzdem8m
    - mapzen
```

I had to change the nz-global configuration part to:
```
# NZ with mapzen fallback.
- name: nz-global
  child_datasets:
    - nzdem8m
    - mapzen
```

There was a space missing between the first dash and name:
`-name: nz-global` => `- name: nz-global`
and I had to remove the dash before `child_datasets`
