### ISSUE TITLE
"Config Error: No dataset folder found at location 'data/etopo1/'"

### ISSUE THREAD

**Issue by 8m0** [ajnisbet/opentopodata#43]
Hello,

I am trying to make etopo1 following this tutorial [ETOPO1](https://www.opentopodata.org/datasets/etopo1/), but I am getting this error: 
`{
  "error": "Config Error: No dataset folder found at location 'data/etopo1/'", 
  "status": "SERVER_ERROR"
}`

My system is Windows 10. I set it through docker.

tiff refactored by GDAL path:
`opentopodata/data/etopo1/ETOPO1.tiff`

config.yaml:

```yaml
# An example of a config.yaml file showing all possible options. If no
# config.yaml file exists, opentopodata will load example-config.yaml instead.


# 400 error will be thrown above this limit.
max_locations_per_request: 100

# CORS header. Should be None for no CORS, '*' for all domains, or a url with
# protocol, domain, and port ('https://api.example.com/'). Default is null.
access_control_allow_origin: null

datasets:
- name: etopo1
  path: data/etopo1/

# Example config for 90 metre SRTM.
# - name: srtm90m
#   path: data/srtm-90m-nasa-v3.0/
#   filename_epsg: 4326  # This is the default value.
#   filename_tile_size: 1  # This is the default value.
```
